# Site settings
title: DotApprove
url: http://dotapprove.lpil.uk
# url: http://www.dotapprove.co.uk

static: http://www.perivan.co.uk/static

# Contact
email: solutions@perivan.co.uk
telephone: +44 (0)20 7562 2222
fax: +44 (0)20 7562 2201
address1: 21 Worship Street
address2: London
address3: EC2A 2DW

# Navigation sections
nav-sections:
  - About Us
  - DotApprove
  - Publishing Tools

excerpt_separator: <!--more-->

paginate: 10
paginate_path: "news/:num"

# Build settings
markdown: kramdown
permalink: /news/:year/:title

exclude:
  - dev_serve.sh
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: :compressed
  sass_dir: _scss

gems:
  - jekyll-sitemap

monthly_archive:
  path: news
